### PR TITLE
Added Task2

### PR DESCRIPTION
**Pull request by PriyamJChakrabarty**
## Issue: #8 

Task2 completed

## Description:

Completed Task 2 - Reformatting the data according to the chat template. My notebook contains the following:

1. **Naive Approach (Old Function)**  
   Initially, I had a simple function that reformats the raw data by splitting the text based on hardcoded "###Human:" and "###Assistant:" markers. However, this approach was a bit fragile and could break with malformed or irregular data.

2. **Improvements in the New Script**  
   In the new version, I’ve:
   - Used **regular expressions (regex)** to reliably split the data into user prompts and model responses. This makes the parsing much more robust.
   - Added **error logging** for malformed entries so that we can easily spot and fix issues in the data.
   - Modularized the code by moving the CSV-saving logic to a separate function, making the code cleaner and easier to maintain.
   - Included **safeguards for missing or empty dataset splits**, so if something’s wrong, it’s clear in the logs.

The goal here was to make the reformatting process more reliable and maintainable while making it easier to debug any issues with the raw data.

### CODE REVIEW

**Comment by Aayushkanjani** [comment]
hey @PriyamJChakrabarty your solution is not visible
is states invalid notebook
can you check it

**Comment by PriyamJChakrabarty** [comment]
Ok let me check once

**Comment by PriyamJChakrabarty** [comment]
@Aayushkanjani I have already checked on VS Code, Local Jupyter Environment and Google Colab....And is working fine. I have made another commit....Can you check it once?

**Comment by Aayushkanjani** [comment]
@PriyamJChakrabarty try creating a new pr
i am closing this one
lets see if it works

**Pull request closed without merging**
